kind: Service
apiVersion: v1
metadata:
  name: __CI_PROJECT_NAME__-__CI_PIPELINE_ID__
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: reveraapi-__CI_PIPELINE_ID__
