apiVersion: v1
kind: Pod
metadata:
  name: __CI_PROJECT_NAME__-__CI_PIPELINE_ID__
  labels:
    app: reveraapi-__CI_PIPELINE_ID__
spec:
  containers:
    - name: __CI_PROJECT_NAME__-__CI_PIPELINE_ID__
      image: __CI_REGISTRY_IMAGE__
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
        name: http
        protocol: TCP
  imagePullSecrets:
    - name: __CI_PROJECT_NAME__-__CI_PIPELINE_ID__
